/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FooterNav: typeof import('./src/components/FooterNav.vue')['default']
    InfoCard: typeof import('./src/components/InfoCard.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    PhotoList: typeof import('./src/components/PhotoList.vue')['default']
    PreviewImage: typeof import('./src/components/PreviewImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCol: typeof import('vant/es')['Col']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanImagePreview: typeof import('vant/es')['ImagePreview']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRow: typeof import('vant/es')['Row']
    VanSwitch: typeof import('vant/es')['Switch']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
